---
- when: systemd_cgroup
  block:
  - name: Change cgroup driver to systemd
    replace:
      path: "{{ item }}/kubelet.service.d/10-kubeadm.conf"
      regexp: '^(ExecStart=)(.*(?=--cgroup-driver))--cgroup-driver=\S*(.*)'
      replace: '\1\2--cgroup-driver=systemd\3'
      backup: yes
    with_items:
      - /usr/lib/systemd/system
      - /var/lib/systemd/system
      - /etc/systemd/system
      - /lib/systemd/system
    failed_when: false
    notify: restart kubelet

  - name: add systemd cgroup driver
    replace:
      dest: "{{ item }}/kubelet.service.d/10-kubeadm.conf"
      regexp: '^((?:ExecStart=)(?:(?!--cgroup-driver=).)+)$'
      replace: '\1 --cgroup-driver=systemd'
      backup: yes
    with_items:
      - /usr/lib/systemd/system
      - /var/lib/systemd/system
      - /etc/systemd/system
      - /lib/systemd/system
    failed_when: false
    notify: restart kubelet

- when: not systemd_cgroup
  block:
  - name: Change cgroup driver to cgroupfs
    replace:
      path: "{{ item }}/kubelet.service.d/10-kubeadm.conf"
      regexp: '^(ExecStart=)(.*(?=--cgroup-driver))--cgroup-driver=\S*(.*)'
      replace: '\1\2--cgroup-driver=cgroupfs\3'
      backup: yes
    with_items:
      - /usr/lib/systemd/system
      - /var/lib/systemd/system
      - /etc/systemd/system
      - /lib/systemd/system
    failed_when: false
    notify: restart kubelet

  - name: add cgroupfs cgroup driver
    replace:
      dest: "{{ item }}/kubelet.service.d/10-kubeadm.conf"
      regexp: '^((?:ExecStart=)(?:(?!--cgroup-driver=).)+)$'
      replace: '\1 --cgroup-driver=cgroupfs'
      backup: yes
    with_items:
      - /usr/lib/systemd/system
      - /var/lib/systemd/system
      - /etc/systemd/system
      - /lib/systemd/system
    failed_when: false
    notify: restart kubelet