---
- name: Create kubernetes repo file if no exists
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: Configure kubernetes.repo
  blockinfile: 
    dest: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ ansible_architecture }}
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
    backup: yes
    insertbefore: EOF

- name: Install kubelet, kubeadm, kubectl, kubernetes-cni
  yum:
    disable_excludes: kubernetes
    name:
      - kubelet{% if version['kubelet'] is defined and version['kubelet'] != 'latest' %}-{{ version['kubelet'] }}{% endif %}
      - kubeadm{% if version['kubeadm'] is defined and version['kubeadm'] != 'latest' %}-{{ version['kubeadm'] }}{% endif %}
      - kubectl{% if version['kubectl'] is defined and version['kubectl'] != 'latest' %}-{{ version['kubectl'] }}{% endif %}
      - kubernetes-cni{% if version['kubernetes_cni'] is defined and version['kubernetes_cni'] != 'latest' %}-{{ version['kubernetes_cni'] }}{% endif %}
    state: present
  notify: kubelet restart

- name: Install systemd-resolved
  when: systemd_resolved
  yum:
    name: systemd-resolved
    state: present
  failed_when: false