---
- name: Ensure downloads/cni directory exists
  when: ansible_hostname == groups['ansible_master'][0]
  become: no
  file:
    path: "{{ local['home'] }}/downloads/cni"
    owner: "{{ local['user'] }}"
    group: "{{ local['user'] }}"
    state: directory
    mode: 0755

- name: install cni network plugin
  include_tasks: "{{ network_plugin }}.yaml"