- name: Configure Bashrc
  lineinfile:
    dest: "{{ target['home'] }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - alias k='kubectl'
    - alias kg='kubectl get'
    - alias kd='kubectl describe'
    - alias ke='kubectl edit'