---
- when: systemd_cgroup
  block:
  - name: Change cgroup driver cgroupfs to systemd
    when: result.stdout | regex_search('^(cgroupDriver:\s*)(cgroupfs)', multiline=True)
    replace:
      dest: /var/lib/kubelet/config.yaml
      regexp: '^(cgroupDriver:)\s*(cgroupfs)'
      replace: '\1 systemd'
      backup: yes
    notify: kubelet restart

  - name: add cgroup driver in kubelet config file
    when: not result.stdout | regex_search('^(cgroupDriver:\s*)(systemd|cgroupfs)', multiline=True)
    lineinfile:
      dest: /var/lib/kubelet/config.yaml
      line: 'cgroupDriver: systemd'
      insertafter: EOF
      backup: yes
    notify: kubelet restart

- when: not systemd_cgroup
  block:
  - name: Change cgroup driver systemd to cgroupfs
    when: result.stdout | regex_search('^(cgroupDriver:\s*)(systemd)', multiline=True)
    replace:
      dest: /var/lib/kubelet/config.yaml
      regexp: '^(cgroupDriver:)\s*(systemd)'
      replace: '\1 cgroupfs'
      backup: yes
    notify: kubelet restart

  - name: add cgroup driver in kubelet config file
    when: not result.stdout | regex_search('^(cgroupDriver:\s*)(systemd|cgroupfs)', multiline=True)
    lineinfile:
      dest: /var/lib/kubelet/config.yaml
      line: 'cgroupDriver: cgroupfs'
      insertafter: EOF
      backup: yes
    notify: kubelet restart