---
- name: Register /var/lib/kubelet/config.yaml file text
  shell: cat /var/lib/kubelet/config.yaml
  register: result
  changed_when: false

- name: set cgroup-driver in kubelet config file
  include: cgroup_driver.yaml

- name: set resolv-confset in kubelet config file
  include: resolv_conf.yaml

- meta: flush_handlers

- name: master node config
  when: ansible_hostname in groups['master']
  include: master.yaml