---
- when: ansible_hostname == groups['ansible_master'][0]
  block:
  - set_fact:
      master_join_completed: true
  - name: check master node join completed
    when: item | int != 0
    set_fact:
      master_join_completed: false
    with_items: >
      [{% for node in groups['master'] %}
      "{{ hostvars[node]['node_state'] }}",
      {% endfor %}]

- when: not hostvars[groups['ansible_master'][0]]['master_join_completed']
  block:
  - name: chmod o+r certificate files
    when:
      - hostvars[groups['ansible_master'][0]]['cert'] is undefined
      - ansible_hostname == groups['ansible_master'][0]
    file:
      path: /etc/kubernetes/pki/{{ item }}
      mode: o+r
    with_items:
      - etcd/ca.crt
      - etcd/ca.key
      - front-proxy-ca.crt
      - front-proxy-ca.key
      - sa.pub
      - sa.key
      - ca.crt
      - ca.key

  - name: include manual_endpoint.yaml
    when:
      - version['kubeadm'] is version('1.16','<',strict=True)
      - ansible_hostname == groups['ansible_master'][0]
    include: manual_endpoint.yaml

  - name: include master.yaml
    when:
      - node_state | int != 0
      - ansible_hostname in groups['master']
      - ansible_hostname != groups['ansible_master'][0]
    include: multi_master.yaml

  - name: chmod o-r certificate files
    when:
      - hostvars[groups['ansible_master'][0]]['cert'] is undefined
      - ansible_hostname == groups['ansible_master'][0]
    file:
      path: /etc/kubernetes/pki/{{ item }}
      mode: o-r
    with_items:
      - etcd/ca.crt
      - etcd/ca.key
      - front-proxy-ca.crt
      - front-proxy-ca.key
      - sa.pub
      - sa.key
      - ca.crt
      - ca.key

- name: kubeadm worker node join
  when:
  - node_state | int != 0
  - ansible_hostname in groups['worker']
  shell: "{{ hostvars[groups['ansible_master'][0]]['join_command'] }}"
  ignore_errors: yes