---
- name: kubelet restart
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted
    enabled: yes
  failed_when: false