---
- name: Ensure kubelet directory exists
  file:
    path: /var/lib/kubelet
    state: directory
    mode: 0700

- name: check node already in cluster
  shell: ls /var/lib/kubelet | grep config.yaml
  register: node_state
  changed_when: false
  failed_when: false

- name: play in ansible_master node
  when: ansible_hostname == groups['ansible_master'][0]
  include: init.yaml