---
- name: Install git(Debian)
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: git{{ '=' + version['git'] if version['git'] != 'latest' else '' }}
    state: "{{ 'present' if version['git'] != 'latest' else 'latest' }}"

- name: Install git(RedHat)
  when: ansible_os_family == "RedHat"
  yum:
    update_cache: yes
    allow_downgrade: yes
    name: git{{ '-' + version['git'] if version['git'] != 'latest' else '' }}
    state: "{{ 'present' if version['git'] != 'latest' else 'latest' }}"