---
- name: Download kube-compose binary
  get_url:
    url: https://github.com/kube-compose/kube-compose/releases/download/v{{ version['compose_util']['kubernetes'] }}/kube-compose.linux
    dest: /usr/local/bin/kube-compose
    owner: root
    group: root
    mode: 0755