---
- name: Ensure downloads directory exists
  when: ansible_hostname == groups['ansible_master'][0]
  file:
    path: "{{ local['home'] }}/downloads"
    owner: "{{ local['user'] }}"
    group: "{{ local['user'] }}"
    state: directory
    mode: 0750