---
- name: Create .vimrc file if not exists
  file:
    path: "{{ target['home'] }}/.vimrc"
    state: touch
    owner: "{{ target['user'] }}"
    group: "{{ target['user'] }}"
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: Configure Vimrc
  lineinfile:
    dest: "{{ target['home'] }}/.vimrc"
    line: "{{ item }}"
  with_items:
  - set ai et ts=2 sw=2 sts=2
  - autocmd FileType * set formatoptions-=o