---
builder:
  - docker
  - kaniko
  # - buildah
  # - podman

version:
  docker: 20.10.7 # If the container runtime is docker, this will be ignored
  kaniko: 1.6.0
  buildah: latest
  podman: latest

kaniko:
  volume:
    path: "{{ local['home'] }}/kaniko/build"
    capacity: 1Gi
    storageClassName: kaniko-volume
    accessModes:
      - ReadWriteOnce