---
builder:
  - docker
  - kaniko

version:
  docker: 20.10.7 # If the container runtime is docker, this will be ignored
  registry: latest
  kaniko: 1.6.0

kaniko:
  volume:
    path: "{{ local['home'] }}/kaniko/build"
    capacity: 1Gi
    storageClassName: kaniko-volume
    accessModes:
      - ReadWriteOnce