---
- name: download the repo file that requires cri-o
  get_url:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ version['cri_o'] }}/{{ ansible_distribution + '_' + os_version }}/devel:kubic:libcontainers:stable:cri-o:{{ version['cri_o'] }}.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{ version['cri_o'] }}.repo
    owner: root
    group: root
    mode: 0644

- name: Install cri-o
  yum:
    update_cache: yes
    name: cri-o
    state: present
  notify: restart cri-o