---
- name: Play RedHat os family tasks
  when: ansible_os_family == "RedHat"
  include_tasks: redhat.yaml

- name: Play Debian os family tasks
  when: ansible_os_family == "Debian"
  include_tasks: debian.yaml

- name: docker group create
  group:
    name: docker
    state: present

- name: Ensure docker directory exists
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: generate docker config file to use systemd driver
  when: systemd_cgroup == true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker 

- name: add docker group on user
  user:
    name: "{{ ansible_env['USER'] }}"
    groups: docker
    append: yes

- meta: flush_handlers