---
- name: Add Docker yum repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Install docker engine latest
  when: version['docker'] == 'latest'
  yum:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  notify: docker service start

- when: version['docker'] != 'latest'
  block:
  - name: List the docker-ce versions available in repo
    shell: yum list docker-ce --showduplicates | sort -r
    register: result

  - name: Get the exact docker-ce version name in yum repo - 1-1
    when:
      - version['docker'] in item
      - "':' in item"
    set_fact:
      yum_docker_ce_version: "{{ item.split(':')[1].split(' ') }}"
    with_items: "{{ result.stdout_lines }}"

  - name: Get the exact docker-ce version name in yum repo - 1-2
    when:
      - version['docker'] in item
      - "not ':' in item"
    set_fact:
      yum_docker_ce_version: "{{ item.split(' ') }}"
    with_items: "{{ result.stdout_lines }}"

  - name: Get the exact docker-ce version name in yum repo - 2
    when:
      - yum_docker_ce_version is defined
      - version['docker'] in item
    set_fact:
      yum_docker_ce_version: "{{ item | trim }}"
    with_items: "{{ yum_docker_ce_version }}"

  - name: List the docker-ce-cli versions available in yum repo
    shell: yum list docker-ce-cli --showduplicates | sort -r
    register: result

  - name: Get the exact docker-ce-cli version name in yum repo - 1-1
    when:
      - version['docker'] in item
      - "':' in item"
    set_fact:
      yum_docker_ce_cli_version: "{{ item.split(':')[1].split(' ') }}"
    with_items: "{{ result.stdout_lines }}"

  - name: Get the exact docker-ce-cli version name in yum repo - 1-2
    when:
      - version['docker'] in item
      - "not ':' in item"
    set_fact:
      yum_docker_ce_cli_version: "{{ item.split(' ') }}"
    with_items: "{{ result.stdout_lines }}"

  - name: Get the exact docker-ce-cli version name in yum repo - 2
    when:
      - yum_docker_ce_cli_version is defined
      - version['docker'] in item
    set_fact:
      yum_docker_ce_cli_version: "{{ item | trim }}"
    with_items: "{{ yum_docker_ce_cli_version }}"

  - name: Install docker engine specific version
    yum:
      update_cache: yes
      allow_downgrade: yes
      name:
        - docker-ce{{ '-' + yum_docker_ce_version if yum_docker_ce_version is defined else '' }}
        - docker-ce-cli{{ '-' + yum_docker_ce_cli_version if yum_docker_ce_cli_version is defined else '' }}
        - containerd.io
      state: present
    notify: docker service start
    failed_when: false