---
- when: registry['ssl']['enable']
  block:
  - set_fact:
      ssl: "{{ ssl | combine({'common_name':registry['name'], 'sub_cert_pass':registry['ssl']['cert_pass']}, recursive=true) }}"
  - include_role:
      name: ssl

- when: registry['auth']['enable']
  block:
  - set_fact:
      auth:  "{{ auth | combine({'file_name':registry['auth']['file_name'], 'account':registry['auth']['account']}, recursive=true) }}"
  - include_role:
      name: authentication

- when: ansible_hostname == groups['ansible_master'][0]
  include: registry.yaml

- include: runtime.yaml

- meta: flush_handlers