---
- when: ansible_hostname == groups['ansible_master'][0]
  block:
  - name: Download binaries
    get_url:
      url: https://github.com/containerd/containerd/releases/download/v{{ version['containerd'] }}/containerd-{{ version['containerd'] }}-linux-amd64.tar.gz
      dest: "{{ local['home'] }}/downloads/containerd.tar"
      owner: "{{ local['user'] }}"
      group: "{{ local['user'] }}"
      mode: 0644

  - name: Unarchive containerd binaries archive
    unarchive:
      src: "{{ local['home'] }}/downloads/containerd.tar"
      dest: "{{ local['home'] }}/downloads"
      owner: "{{ local['user'] }}"
      group: "{{ local['user'] }}"
      mode: 0755

- name: Copy containerd binaries in PATH
  copy:
    src: "{{ local['home'] }}/downloads/bin/"
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755

- name: Add containerd service
  copy:
    src: containerd.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644

- name: Ensure containerd config folder exists
  file:
    path: /etc/containerd
    state: directory
    mode: 0750

- name: Generate default containerd config file
  template:
    src: config.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
  notify: containerd_restart

- meta: flush_handlers