---
- name: runtime install
  when: item['install']
  include_role:
    name: "{{ item['name'] }}"
  with_items:
    - { name: runtime/roles/containerd, install: "{{ runtime == 'containerd' }}" }
    - { name: runtime/roles/docker, install: "{{ runtime == 'docker' }}" }
    - { name: runtime/roles/cri-o, install: "{{ runtime == 'cri-o' }}" }