- name: Configure Bashrc
  lineinfile:
    dest: "{{ target['home'] }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "alias ans='ansible'"
    - "alias anp='ansible-playbook'"
    - "alias ang='ansible-galaxy'"
    - "alias anv='ansible-vault'"