---
- name: restart docker 
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: restart cri-o
  systemd:
    name: crio
    state: restarted
    enabled: yes

- name: restart podman.socket
  systemd:
    name: podman.socket
    state: restarted
    enabled: yes
  failed_when: false