---
- when: ansible_hostname == groups['ansible_master'][0]
  block:
  - name: Download docker binary files
    get_url:
      url: https://download.docker.com/linux/static/stable/x86_64/docker-{{ version['docker'] }}.tgz
      dest: "{{ local['home'] }}/downloads/docker-{{ version['docker'] }}.tgz"
      owner: "{{ local['user'] }}"
      group: "{{ local['user'] }}"
      mode: 0644

  - name: Unarchive docker binary files
    unarchive:
      src: "{{ local['home'] }}/downloads/docker-{{ version['docker'] }}.tgz"
      dest: "{{ local['home'] }}/downloads"
      owner: "{{ local['user'] }}"
      group: "{{ local['user'] }}"
      mode: 0775

- name: copy docker binary files in path
  copy:
    src: "{{ local['home'] }}/downloads/docker/{{ item }}"
    dest: "/usr/bin"
    owner: root
    group: root
    mode: 0775
  with_items:
    - docker
    - dockerd
    - docker-init
    - docker-proxy
  failed_when: false