---
- name: docker install
  when: runtime != 'docker'
  include: install.yaml

- name: docker config
  when: runtime != 'docker'
  include: config.yaml

- name: docker registry
  when: docker_registry is defined and docker_registry
  include: registry.yaml