---
- name: get inferfaces name
  set_fact:
    ifaces: "{{ ansible_interfaces | difference(['lo', 'docker0']) }}"

- name: get interface name which on ansible host ip
  when: ansible_facts[item]['ipv4']['address'] is defined and ansible_facts[item]['ipv4']['address'] == ansible_host
  set_fact:
    iface: "{{ item }}"
  with_items: "{{ ifaces }}"