---
- name: ansible ssh settings
  hosts: cluster
  serial: 1
  roles:
  - role: common/target/default
  - role: ssh
  ### root user ssh key trade ###
  # - role: common/target/root
  # - role: ssh

- name: custom settings
  hosts: cluster
  gather_facts: no
  become: yes
  roles:
  - role: custom/motd
  - role: common/target/default
  - role: custom/vim/vim-plugins
  - role: custom/vim/vim-custom
  - role: custom/git
  - role: custom/alias

  - role: common/target/root
  - role: custom/vim/vim-plugins
  - role: custom/vim/vim-custom
  - role: custom/git
  - role: custom/alias

- name: kubernetes install
  hosts: cluster
  gather_facts: no
  become: yes
  roles:
  - role: runtime
  - role: kubernetes

- name: utils, components install
  hosts: cluster
  gather_facts: no
  become: yes
  roles:
  # - role: utils/k9s
  # - role: utils/stern
  # - role: utils/dashboard
  # - role: utils/builder
  # - role: utils/skopeo
  # - role: utils/compose
  - role: registry
  - role: helm
  - role: metallb
  - role: ingress-controller
  tasks:
  - when: alert is defined and alert != ''
    name: alert
    debug:
      msg: "{{ alert }}"