---
- name: ansible ssh settings
  hosts: cluster
  gather_facts: yes
  serial: 1
  roles:
    - role: commons/target/default
    - role: ssh
    - role: commons/target/root
    - role: ssh

- name: kubernetes install, custom settings
  hosts: cluster
  gather_facts: no
  become: yes 
  roles:
    - role: commons/target/default
    - role: custom/alias
    - role: custom/vim/vim
    - role: custom/vim/vim-plugins
    - role: custom/vim/vim-custom
    - role: commons/target/root
    - role: custom/alias
    - role: custom/vim/vim-plugins
    - role: custom/vim/vim-custom
    - role: custom/git
    - role: custom/motd
    - role: runtime
    - role: kubernetes
    - role: builder