---
- name: ansible ssh settings
  hosts: cluster
  gather_facts: yes
  serial: 1
  roles:
  - role: common/target/default
  - role: ssh
  - role: common/target/root
  - role: ssh

- name: kubernetes install, custom settings
  hosts: cluster
  gather_facts: no
  become: yes 
  roles:
  - role: utils/git
  - role: utils/vim
  - role: custom/motd

  - role: common/target/root
  - role: custom/vim/vim-plugins
  - role: custom/vim/vim-custom
  - role: custom/git
  - role: custom/alias

  - role: common/target/default
  - role: custom/vim/vim-plugins
  - role: custom/vim/vim-custom
  - role: custom/git
  - role: custom/alias

  - role: runtime
  - role: kubernetes
  - role: builder
  - role: utils/skopeo
  - role: utils/compose
  - role: registry
  - role: metallb
  - role: ingress-controller