---
version:
  nginx: 1.21.5
  registry: 2.7.1

registry:
  docker:
    enable: yes
    common_name: m1.dev
    hosts:
    - '@'
    - registry
    ssl:
      enable: yes
      cert_pass: docker registry is a private container repository
    allow_delete: yes
    auth:
      enable: yes
      file_name: .registry
      account:
      - name: admin
        password: admin
    volume:
      path: /data/registry
      capacity: 5Gi
      storageClassName: registry-volume
      accessModes:
      - ReadWriteOnce
  chartmuseum:
    enable: yes
    ssl:
      enable: no