---
- name: Disable swap for current session
  command: swapoff -a
  become: true

- name: swapoff permanent
  replace:
    dest: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes

- name: Create k8s.conf file if no exists
  file:
    path: /etc/modules-load.d/k8s.conf
    state: touch
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: write modules in k8s.conf file
  lineinfile:
    dest: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: Load overlay & br_netfilter module
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Create k8s.conf file if no exists
  file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: apply sysctl entries
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_items:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Play RedHat os family tasks
  when: ansible_os_family == "RedHat"
  include_tasks: redhat.yaml